---
# Playbook para comprobar que esté levantado postgresql
- hosts: databases
  remote_user: freemem
  become: yes
  tasks:
    - name: check postgresql
      service:
        name: postgresql 
        state: started
